### ISSUE TITLE
[BUG] Backup Fails (Probably With Remote MySQL as the Cause)

### ISSUE THREAD

**Issue by gabotronix** [litespeedtech/cyberpanel#909]
**Describe the bug**
CyberPanel fails to perform a local backup. The error message in the CyberPanel Main Log File stated:

`[06.27.2022_22-34-18] The connection rootdb doesn't exist [207][5009]`

I checked the mysql credentials from SSH via `cat /etc/cyberpanel/mysqlPassword`, then manually tried to log in via `mysql -u admin -h remote_mysql_IP -p`. The connection was successful.

**To Reproduce**
1. From CyberPanel: Main » Backup » Create Backup
2. Select website from the list that you want to backup.
3. Select backup destination (Home).
4. Click _Create Backup_.

**Expected behavior**
The backup status should have been shown. Instead, it was as if nothing happened. Upon checking the backup folder from SSH, it was empty:

```bash
# ls -l /home/domain.com/backup/backup-domain.com-06.27.2022_22-34-18/
total 0

# du -sh /home/domain.com/backup/
12K     /home/domain.com/backup/
```

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.3, build 2

**Additional context**
For the remote database, I am using MariaDB 10.6 with [Unix socket authentication](https://mariadb.com/kb/en/authentication-plugin-unix-socket/). It allows the authenticated root SSH user to log in as root MySQL user without a password.

In order to install CyberPanel, I created a separate `admin user` with the same root mysql privileges on the remote database server. The steps to create the `admin user` were as follows:
```bash
mysql -u root
   CREATE USER admin@cyberpanel_server_IP IDENTIFIED BY 'desired_admin_password';
   GRANT ALL PRIVILEGES ON *.* TO admin@cyberpanel_server_IP;
   GRANT ALL PRIVILEGES ON  *.* TO 'admin'@'cyberpanel_server_IP' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
   FLUSH PRIVILEGES;
   quit
```

**Comment by usmannasir** [comment]
Your CyberPanel `settings.py` have correct details of MySQL logins? Also what do you have in `cat /etc/cyberpanel/mysqlPassword` you can hide passwords but paste the rest here?

Also I assume your CP is working fine.

**Comment by gabotronix** [comment]
@usmannasir 

Yes, the entire CP is working fine, or at least the menus that I use the most (create website, create database, open ports in CSF, add Let's Encrypt SSL). Only Backup seems to not work.

Here is the Database setting in CyberPanel settings.py
```bash
less /usr/local/CyberCP/CyberCP/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cyberpanel',
        'USER': 'cyberpanel',
        'PASSWORD': 'cyberpanel_password',
        'HOST': 'IP_of_Remote_SQL',
        'PORT':'3306'
    },
    'admindb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysql',
        'USER': 'admin',
        'PASSWORD': 'admin_password',
        'HOST': 'IP_of_Remote_SQL',
        'PORT':'3306',
    },
}
```

Here is `cat /etc/cyberpanel/mysqlPassword`
```bash
{"remotemysql": "ON", "mysqlhost": "IP_of_Remote_SQL", "mysqldb": "", "mysqluser": "admin", "mysqlpassword": "admin_mysql_password", "mysqlport": "3306"}
```

**Comment by usmannasir** [comment]
OK. I will check, since this is remote backup case it can take some time.

**Comment by gabotronix** [comment]
@usmannasir,

Thanks. I'd like to clarify that I am not performing a remote backup. I am doing a local backup using `remotemysql` as the database configuration.

**Comment by kenny-nt** [comment]
Have the same issue... My errors is: 
My CP server private IP: 10.0.0.3 and remote DB server is: 10.0.0.4
`mysqldump: Got error: 1045: "Access denied for user 'admin_user'@'10.0.0.3' (using password: YES)" when trying to connect`

Looked in /usr/local/CyberCP/CyberCP/settings.py >>>
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cyberpanel',
        'USER': 'cyberpanel',
        'PASSWORD': 'randompassofcyberpanel',
        'HOST': '10.0.0.4',
        'PORT':'3306',
        'OPTIONS':  {
            'ssl': {},
        }        
    },
    'rootdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysql',
        'USER': 'admin_user',
        'PASSWORD': 'A_Really_Strong_Password',
        'HOST': '10.0.0.4',
        'PORT': '3306',
        'OPTIONS':  {
            'ssl': {},
        }        
    },
}
```
Checked OK with command.
`mysql -u admin_user -pA_Really_Strong_Password -h 10.0.0.4`
All function is working normally. Create database > database still created on remote server.

I think mysqlUtilities.py have something wrong with:
def createDatabaseBackup

**Comment by usmannasir** [comment]
@khanh-nt Remote MySQL need an expert to manage the server. As you can see the error is clear 

`mysqldump: Got error: 1045: "Access denied for user 'admin_user'@'10.0.0.3' (using password: YES)" when trying to connect`

**Comment by kenny-nt** [comment]
> @khanh-nt Remote MySQL need an expert to manage the server. As you can see the error is clear 
> 
> 
> 
> `mysqldump: Got error: 1045: "Access denied for user 'admin_user'@'10.0.0.3' (using password: YES)" when trying to connect`

Yes, I know what the error mean but I wonder why it is like that.

As in mysqlUltilities.py

```
command = 'mysqldump --defaults-extra-file=/home/cyberpanel/.my.cnf -u %s --host=%s --port %s %s' % (mysqluser, mysqlhost, mysqlport, databaseName)
cmd = shlex.split(command)

```
And /home/cyberpanel/.my.cnf content:

```
[mysqldump]
user=admin_user #I changed from root to admin_user
password=A_Really_Strong_Password
max_allowed_packet=1024M

[mysql]
user=admin_user #I changed from root to admin_user
password=A_Really_Strong_Password

```

So why have that error!? Is that error mean wrong password?
Updated: @usmannasir 
I have test via SSH and it working without any problems...
` mysqldump --defaults-extra-file=/home/cyberpanel/.my.cnf -u admin_user --host=10.0.0.4 --port 3306 testdb > /root/testdb.sql`

**Comment by kenny-nt** [comment]
@usmannasir 
My problem is solved by add "" to password in .my.cnf file:
[mysqldump]
password="Should#P@$$"

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.
